version: '3.4'

services:
  node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.4.5-bionic
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
