export * as authService from './auth.service'
export * as tokenService from './token.service'
export * as mailService from './mail.service'
export * as userService from './user.service'
export * as roleService from './role.service'
export * as rightService from './right.service'
